# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches: [ "main" ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
      - uses: actions/setup=node@v1
        with:
          node-version: 14.x
      - run: npm i
      - run: npm runnum build --if-preset
      - run: npm start
     
